; Configuration file for RepRapFirmware on Duet 3 Main Board 6XD
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.2+6 on Thu Feb 15 2024 17:10:57 GMT+0000 (Greenwich Mean Time)

; CAN bit rate
M952 B0 S1000                                                            ; Set CAN bit rate to 500kB/s (from 1MB/s)
G4 S2                                                                   ; wait for expansion boards to boot up

; Variables
M98 P"variables.g"                                                      ; Initialise ALL variables

; -------------------------------------------------------------------------- SBC Boot Config ------------------------------------------------------------------------

M291 P"Applying persistent configuration options" R"Please wait" S1 T60 ; show that persistent settings are being configured
while exists(sbc) && plugins.DuetPiManagementPlugin.pid < 0 && iterations < 30
  G4 S2                                                                 ; wait for DuetPiManagementPlugin to become available
G4 S2                                                                   ; wait another moment
M550 P"EvoOne"                                                          ; set hostname
M586 P0 S1 C"*"                                                         ; configure HTTP & enable CORS
M586 P1 S0                                                              ; disable FTP
M586 P2 S1                                                              ; enable Telnet
M292                                                                    ; hide message box again upon completion
