; homev.g
; called to home the V axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.2+6 on Thu Jan 25 2024 09:21:37 GMT+0000 (Greenwich Mean Time)

;G92 V{state.restorePoints[0].coords[4]} ; Set to saved position
G92 V0