; homew.g
; called to home the W axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.2+6 on Thu Jan 25 2024 09:21:37 GMT+0000 (Greenwich Mean Time)

;G92 W{state.restorePoints[0].coords[5]} ; Set to saved position
G92 W0