; tpre2.g
; called before tool 2 is selected
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Tue Nov 14 2023 16:00:20 GMT+0000 (Greenwich Mean Time)

;M118 P0 S{"Pre.g Next Tool: "^(state.nextTool)} L2