; homea.g
; called to home the A axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.2+6 on Thu Jan 25 2024 09:21:37 GMT+0000 (Greenwich Mean Time)

G91
M564 S0 H0
G0 A-12
G92 A0
M564 S1 H1
G90

if state.currentTool == 2 ; if filament LEFT selected
    G0 A{global.filLEFTExtend}
    set global.tool = "filament LEFT"