; homeb.g
; called to home the B axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.2+6 on Thu Jan 25 2024 09:21:37 GMT+0000 (Greenwich Mean Time)

G91
M564 S0 H0
G0 B-12
G92 B0
M564 S1 H1
G90

if state.currentTool == 3 ; if filament RIGHT selected
    G0 B{global.filRIGHTExtend}
    set global.tool = "filament RIGHT"