; homeu.g
; called to home the U axis
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.2+6 on Thu Jan 25 2024 09:21:37 GMT+0000 (Greenwich Mean Time)

G92 U{state.restorePoints[0].coords[3]} ; Set to saved position